version: "3.8"
services:
  db:
    env_file:
      - .env
    container_name: "db_test"
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPass}
      - POSTGRES_DB=${DBName}
    ports:
      - "${DBPort}:5432"
    #    volumes:
    #      - ../backup02-10.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
    networks:
      - custom
networks:
  custom:
    driver: bridge